### ISSUE TITLE
to ticket or not to ticket

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#11]
this is  a question i want to discuss once.

we have this options:
1. free for all, fully sponsored
   - \+ lowest barrier for entrance
   - \+ no/few financial administration required
   - \- expected rate of non-appearances is higher
2. deposit fee, fully sponsored
   - \+ registration is more binding and reliable
   - \- more financial administration is required (including possible lawering)
3. cheap ticket, partly sponsored
   - \+ same as 2.
   - \+ less dependent from sponsors
   - \- people have to pay for it.

thoughts?

**Comment by greelgorke** [comment]
at the moment i prefer option 1. but i'm open to arguments

**Comment by usefulthink** [comment]
the main question would be how big our investment per person will be. That basically determines if there is a need to reduce the no-show rate by some sort of deposit.

I would really prefer option 1. - it should be no problem to get a location and some drinks sponsored.

**Comment by fgnass** [comment]
I also prefer option 1. Having free tickets on https://ti.to (or a similar platform) would probably be a good idea.

**Comment by mdunisch** [comment]
I would prefer the **2nd option**. I mean: even if the ticket only cost 1€ it might be a little bit more reliable. I'm a little bit afraid of in the end people they wanted to join can't contribute because of so many people getting a ticket and don't come because it's for free.

Maybe something for the lawering-problem: What about you have to donate say 1€ to Mozilla Foundation or Apache Foundation or something like that. So we aren't in charge for this money thing. But  I don't know if there is any Onlineservice for that ;-)

But my 2nd choose would be **option 1)**

**Comment by fgnass** [comment]
We could invite people to come even if they didn't get a (free) ticket and put them on a waiting list like HH.JS does. We should also encourage the ones who RSVP'd to return their tickets if they can't make it to the event.

**Comment by greelgorke** [comment]
the problem with the invitation and waiting lists, as in HH.js and node.HH is, that it just doesnt work in practice. last 2 node.hh had over 40 rsvps but 20-30 appeared. thats ok for a talk night, especially when you have not tha much costs (assuming a non-rented room and drinks payed by usage.) But in the event with longer runtime, catering, setup efforts (wifi and workstations) the drop out rate should be less.

The only real concern with the option 2 i have is to manage all the money and refunding. if services like ti.to can manage this for me as a trust fund, i'm fine with it. i would donate the left over money then, may be via gittip for some Node.js contributors.

**Comment by fgnass** [comment]
Since we all want this event to be as open and accessible as possible, we could only charge a very tiny amount. It would have to be so small, that people probably wouldn't even care if we donated their fee.

What about writing something like the following in big letters above the "Get a Ticket" button instead?
- Don't get yourself a ticket unless you are absolutely sure you'll make it.
- Don't worry, we won't sell out. Tickets will be available until xx.11. (5 days before the event)
- If you've got a ticket but can't make it, return it here: http://....
- If you don't show up without doing so your name will end up in the NodeSchool Klassenbuch. Names in there might have it harder to get a ticket for future events. Also bad karma. And maybe a public call out on Twitter ;)

**Comment by afknapping** [comment]
some 1st + 2nd hand experiences:
- "real" tickets (tito, amiando, eventbrite) are good, because feels valuable
- free is good
- a waitinglist is good
- overbooking capacitiy is good to make up for noshows (maybe 10% for the start, if no show rate is higher, adjust at follow-up events)
- no fee is high enough to prevent no-shows. that only starts in the hundreds of bucks. if people do not feel well, they will just not show up, doesn't matter if ticket is 0 or 60 eur.
- reminding attendees constantly to cancel their tickets if they cannot make it is good (they just forget/verpeil, it's never bad intent or whatever-ness)
- canceling must be painless, otherwise people won't bother.
- rule #1 on money: don't do it. find a location sponsor who
  - is also willing to do drinks too (they can just order some with their other weekly order
  - where you can use the wifi
- really, try to run the event without handling any money yourself. the pain is endless.
- don't do catering, people can grab lunch or diner themselves (it's just a couple hours, so they can grab sth to eat before/after)
- in general, keep it small, keep it lean, keep it fun :)

i do not get the "setup workstations and wifi" thing.

**Comment by timoxley** [comment]
> the problem with the invitation and waiting lists … over 40 rsvps but 20-30 appeared

We had same problem in singapore. 85 people rvsped, 40+ people on waitlist begging me to open up a slot for them… then only ~35 people showed up, meaning those people on the waitlist missed out needlessly.

We went from ~50% no-shows to ~10% no-shows at the next event simply by charging a few dollars ($10 SGD) which we were able to use to purchase refreshments for attendees.

**Comment by greelgorke** [comment]
I think, free entrance and begging for good behavior just don't work well. when you can't plan a bit, it doesn't matter if ppl are either evil, lazy or lost their heads and didn't cancel in a proper way. 

Still, i'm not that comfortable with handling money in any case, yet. Having a ticket, even if it's free, may do some positive.

With Catering, i don't mean a full blown thing, with serving etc. i'm thinking about refreshments and something delivered near noon for a small buffet. i have a sponsor for that already, btw.

**Comment by usefulthink** [comment]
i am completely +1 for the ideas here and think that suggestions from @fgnass and @filtercake on communicating the problem with no-shows should be enough to have a quite reliable approximation how many people will show up.

Also very much in favour of

> rule #1 on money: don't do it.

**Comment by olizilla** [comment]
For what it's worth, we used to do free tickets + all sponsored at nodeschool london, but we switched to small ticket fee + no sponsors. 

The main reason was with free tickets we had roughly 50% of people not show up. For that last event we charged £5 per ticket and > 90% of them turned up. We spent the money on fruit, veg and dips, for maximum brain energy to cost per kg!  Everyone was eating bananas and solving problems ;-)

We had a small surplus left over of about £30, which we're gonna put towards stickers for the next event.

**Comment by afknapping** [comment]
@olizilla @timoxley thx for the input. good to know that ticket fees actually _do_ help in this context :)

**Comment by greelgorke** [comment]
@olizilla how do you handle the financial stuff then? i don't realy want to be personally accountable for the money tbh

**Comment by olizilla** [comment]
We don't have a good solution for that yet. The tickets are through tito, the money sits in stripe and a slice gets taken off for processing fees. We are responsible for it, and we'll have to come up with some structure for dealing with it. We ran the last one as a test, and it worked for us, so we'll be figuring out the rest as we go.

**Comment by mdunisch** [comment]
I would say let's make the tickets free for our first event and just offer a few more tickets than we have place for people.

I really like the idea of a very small price but I'm totally with @greelgorke - handling the money is really pain. 

Because we only have 30 days left: Just start our first event and let's see how it works - we can make ticket fees in the future!

**Comment by greelgorke** [comment]
@mdunisch yes free tickets pls
